# This file is generated by scripts/desktop-cask.sh on release. DO NOT EDIT.
cask "pr-manager-desktop" do
  version "0.1.6"
  sha256 "ee50ce5aac318553cf7dd33ddd2186615f28b3e052b114c3d01dad8c1a42c8ac"

  url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/PR-Manager-macos-arm64.zip"
  name "PR Manager"
  desc "Desktop app that sorts pull request changes by the human review they need"
  homepage "https://github.com/amitbet/pr-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on arch: :arm64
  depends_on formula: [
    "gh",
    "git",
  ]

  app "PR Manager.app"

  # The app is ad-hoc signed but not notarized.
  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/PR Manager.app"]
  end

  caveats <<~EOS
    Run `gh auth login` before opening PR Manager.
  EOS
end
