# This file was generated by GoReleaser. DO NOT EDIT.
cask "pr-manager" do
  version "0.1.8"

  on_macos do
    on_arm do
      sha256 "64231abe4cfed74f31103e42189f055abc365eae1f2a1b9842ffe882a2edc3b0"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4ed6f9023a7cfda4cd8505a1f1002a5a6d9c1e219a489aeb39c9e829cd929f37"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5abc7c6529fcf2d3b9f5472f610db9face4c97b008a9f34980a8032fad90b7c5"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f22103a53722381d4dacf8730d902ac6e5a41147c8973493d44ab0a5eb5ec241"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pr-manager"
  desc "Sort pull request changes by the human review they need"
  homepage "https://github.com/amitbet/pr-manager"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "git",
    ]

  binary "pr-manager"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pr-manager"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `gh auth login`, then `pr-manager serve`.
    Install Go for full Go call graphs; otherwise indexing uses declarations only.
  EOS
end
