# This file was generated by GoReleaser. DO NOT EDIT.
cask "pr-manager" do
  version "0.1.5"

  on_macos do
    on_arm do
      sha256 "9ffc6caacd0d65cfd89aaee10f5e454569fdafb8e6e5fa303ac8b4f4bcb0ec0d"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b980ec19400a4d866f199b757d706690e89644d54ae41739902bb7f9e3803ce7"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b79da745b884e7072fd60cc63a15a7492cbd03e4619e6803b4e9af1bca4f5be4"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3be086d2bcb16454b4ee5cfff1ba33ff54fe030cded4d5c2a56de0a5bf42b861"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pr-manager"
  desc "Sort pull request changes by the human review they need"
  homepage "https://github.com/amitbet/pr-manager"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "git",
    ]

  binary "pr-manager"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pr-manager"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `gh auth login`, then `pr-manager serve`.
    Install Go for full Go call graphs; otherwise indexing uses declarations only.
  EOS
end
