# This file is generated by scripts/desktop-cask.sh on release. DO NOT EDIT.
cask "pr-triage-desktop" do
  version "0.1.1"
  sha256 "3e205ec881e5ec3c89aaf259c29865494c46248cc5cf91c7f6d94c3a38aae823"

  url "https://github.com/amitbet/pr-triage/releases/download/v#{version}/PR-Triage-macos-arm64.zip"
  name "PR Triage"
  desc "Desktop app that sorts pull request changes by the human review they need"
  homepage "https://github.com/amitbet/pr-triage"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on arch: :arm64
  depends_on formula: [
    "gh",
    "git",
  ]

  app "PR Triage.app"

  # The app is ad-hoc signed but not notarized.
  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/PR Triage.app"]
  end

  caveats <<~EOS
    Run `gh auth login` before opening PR Triage.
  EOS
end
