# This file was generated by GoReleaser. DO NOT EDIT.
cask "pr-triage" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "f6cb0d523d0ca39f3c13214c77163252355580cba138ae55adc4aa9ac6126396"
      url "https://github.com/amitbet/pr-triage/releases/download/v#{version}/pr-triage_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e6ac9c89112d6948ddea9f8ffc463dfdafbd301b2227ad8f01d25419bcff7f5f"
      url "https://github.com/amitbet/pr-triage/releases/download/v#{version}/pr-triage_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d1d737691f67c9dcd4cd6cedd1264b8237ea4d1dd50db7934030c03f07369689"
      url "https://github.com/amitbet/pr-triage/releases/download/v#{version}/pr-triage_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "552bfe43849ad8575832752624d327d359b3c8f7692ea51d95b27c35616dc540"
      url "https://github.com/amitbet/pr-triage/releases/download/v#{version}/pr-triage_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pr-triage"
  desc "Sort pull request changes by the human review they need"
  homepage "https://github.com/amitbet/pr-triage"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "git",
    ]

  binary "pr-triage"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pr-triage"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `gh auth login`, then `pr-triage serve`.
    Install Go for full Go call graphs; otherwise indexing uses declarations only.
  EOS
end
