# This file was generated by GoReleaser. DO NOT EDIT.
cask "pr-triage" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "9f643357908898397b88fbd5006a618845fe23c9cdbf0d4cd0c1d129d7080096"
      url "https://github.com/amitbet/pr-triage/releases/download/v#{version}/pr-triage_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7666671be7bd4a3fd21a07c4ba5f03ad407037eea07209148c651cf393b4d5e3"
      url "https://github.com/amitbet/pr-triage/releases/download/v#{version}/pr-triage_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7969dfda448ff5e0ecbb5f10248fb1d651e8f9339f1e3438ef5abb8dbc153ad4"
      url "https://github.com/amitbet/pr-triage/releases/download/v#{version}/pr-triage_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2da2a465c80dbac97e2fa35b009cec7984e3e22d65b195b7dfe6a466a6b3d50e"
      url "https://github.com/amitbet/pr-triage/releases/download/v#{version}/pr-triage_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pr-triage"
  desc "Sort pull request changes by the human review they need"
  homepage "https://github.com/amitbet/pr-triage"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "git",
    ]

  binary "pr-triage"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pr-triage"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `gh auth login`, then `pr-triage serve`.
    Install Go for full Go call graphs; otherwise indexing uses declarations only.
  EOS
end
