# This file was generated by GoReleaser. DO NOT EDIT.
cask "pr-triage" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "522b6a620566eee08105d123bbbecefbdecd3dcf0f84ad56185fc1c6a97a745f"
      url "https://github.com/amitbet/pr-triage/releases/download/v#{version}/pr-triage_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "78cd070f79719cafe131c301df2fe7197340219dc5f7f9946c30784d1f61def2"
      url "https://github.com/amitbet/pr-triage/releases/download/v#{version}/pr-triage_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0ea61e9bcb17d76877a646c569dab0c1939afab7627149ed73833e9b11638a9c"
      url "https://github.com/amitbet/pr-triage/releases/download/v#{version}/pr-triage_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4491953bf885c887fe8dbbaf42d765f19c89f616457b8d03d1df218297be0899"
      url "https://github.com/amitbet/pr-triage/releases/download/v#{version}/pr-triage_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pr-triage"
  desc "Sort pull request changes by the human review they need"
  homepage "https://github.com/amitbet/pr-triage"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "git",
    ]

  binary "pr-triage"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pr-triage"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `gh auth login`, then `pr-triage serve`.
    Install Go for full Go call graphs; otherwise indexing uses declarations only.
  EOS
end
