#!/usr/bin/env bash
# Writes the Homebrew cask for the macOS desktop app to stdout.
# Usage: desktop-cask.sh VERSION PATH/TO/PR-Triage-macos-arm64.zip
set -euo pipefail
version=${1#v}
sha=$(shasum -a 256 "$2" | cut -d' ' -f1)

cat <<CASK
# This file is generated by scripts/desktop-cask.sh on release. DO NOT EDIT.
cask "pr-triage-desktop" do
  version "$version"
  sha256 "$sha"

  url "https://github.com/amitbet/pr-triage/releases/download/v#{version}/PR-Triage-macos-arm64.zip"
  name "PR Triage"
  desc "Desktop app that sorts pull request changes by the human review they need"
  homepage "https://github.com/amitbet/pr-triage"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on arch: :arm64
  depends_on formula: [
    "gh",
    "git",
  ]

  app "PR Triage.app"

  # The app is ad-hoc signed but not notarized.
  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/PR Triage.app"]
  end

  caveats <<~EOS
    Run \`gh auth login\` before opening PR Triage.
  EOS
end
CASK
